# Generated by Django 3.1.3 on 2020-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
